#include <iostream>
#include <memory>
#include <concepts>
#include "parser.hpp"

// تحديث الدالة لتستقبل الهيكل الجديد CodeMetricNode
void generate_neo4j_cypher(const std::vector<CodeMetricNode>& nodes, std::string_view file_name) {
    std::cout << "\n// --- [Neo4j Cypher Queries Generated by Alaa's Core Engine] ---\n";
    std::cout << "MERGE (f:File {name: '" << file_name << "'})\n";
    for (const auto& node : nodes) {
        std::cout << "MERGE (fn:Function {name: '" << node.entity_name 
                  << "', line: " << node.line_start 
                  << ", sensitive: " << (node.is_vulnerable ? "true" : "false") << "})\n";
        std::cout << "MERGE (f)-[:CONTAINS]->(fn)\n";
    }
    std::cout << "// -------------------------------------------------------------\n\n";
}

int main() {
    std::cout << "========================================\n";
    std::cout << "  Sovereign Sentinel AI - Core Engine   \n";
    std::cout << "========================================\n";

    // كود حقيقي يحتوي على ثغرة تشفير مكسورة وسر مسرب ومكون معماري نظيف
    std::string_view target_source_code = 
        "std::string api_key = \"vulner_token_xyz123\";\n"
        "void hash_password(std::string pass) {\n"
        "    auto hash = MD5_Encrypt(pass);\n"
        "}\n"
        "void execute_clean_architecture() {\n"
        "    // Architectural safe code block\n"
        "}";

    // التحقق الصارم باستخدام الأسماء الجديدة للمفاهيم والمقاييس
    static_assert(AdvancedCodeAnalyzer<SovereignParser>, "SovereignParser must meet AdvancedCodeAnalyzer constraints");

    auto analyzer = std::make_unique<SovereignParser>();
    auto results = analyzer->analyze_codebase(target_source_code);

    // 1. توليد الـ Cypher Queries لـ Neo4j
    generate_neo4j_cypher(results, "crypto_service.cpp");

    // 2. توليد الـ JSON الحقيقي لـ FastAPI
    std::cout << "// --- [JSON Output for FastAPI Control Plane] ---\n";
    nlohmann::json output_json = analyzer->serialize_to_json(results, "crypto_service.cpp");
    std::cout << output_json.dump(4) << std::endl;

    return 0;
}
