#include <iostream>
#include <memory>
#include <concepts>
#include "parser.hpp"

void generate_neo4j_cypher(const std::vector<FunctionNode>& nodes, std::string_view file_name) {
    std::cout << "\n// --- [Neo4j Cypher Queries Generated by Alaa's Core Engine] ---\n";
    std::cout << "MERGE (f:File {name: '" << file_name << "'})\n";
    for (const auto& node : nodes) {
        std::cout << "MERGE (fn:Function {name: '" << node.name 
                  << "', line: " << node.line_number 
                  << ", sensitive: " << (node.is_security_sensitive ? "true" : "false") << "})\n";
        std::cout << "MERGE (f)-[:CONTAINS]->(fn)\n";
    }
    std::cout << "// -------------------------------------------------------------\n\n";
}

int main() {
    std::cout << "========================================\n";
    std::cout << "  Sovereign Sentinel AI - Core Engine   \n";
    std::cout << "========================================\n";

    std::string_view mock_code = "void login_user() {}\nvoid run_analysis() {}";
    
    static_assert(CodeParser<MicroParser>, "MicroParser must comply with CodeParser concept");

    auto parser = std::make_unique<MicroParser>();
    auto functions = parser->parse_functions(mock_code);

    generate_neo4j_cypher(functions, "auth.cpp");
    return 0;
}
